version: 1.5.0.{build}
os: Visual Studio 2019
skip_tags: true
environment:
  Major: 1
  Minor: 5
  Patch: 0
configuration: Release
services: mongodb
before_build:
- .\bootstrap.cmd
build:
  project: master.proj
  verbosity: minimal
test: off
artifacts:
- path: Build\*.nupkg
