name: Build Project

env:
  BUILD_PATH: '${{github.workspace}}/publish'
  BUILD_VERSION: '2.0.${{github.run_number}}'
  BUILD_INFORMATION: '2.0.${{github.run_number}}+Branch.${{github.ref_name}}.Sha.${{github.sha}}'

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: 'dotnet build --no-restore --configuration Release -p:Version="${{env.BUILD_VERSION}}" -p:InformationalVersion="${{env.BUILD_INFORMATION}}"'

      - name: Publish Web Application
        if: success()
        run: 'dotnet publish ./src/EstimatorX.Service/EstimatorX.Service.csproj --no-build --configuration Release --output "${{env.BUILD_PATH}}/Application"'

      - name: Upload Web Application Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: Application
          path: '${{env.BUILD_PATH}}/Application'

  deploy-website:
    runs-on: ubuntu-latest
    needs: build-project
    if: success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')

    steps:
      - name: Download Web Application Artifact
        uses: actions/download-artifact@v2
        with:
          name: Application

      - name: Deploy Web Application to Azure Staging
        if: github.ref == 'refs/heads/develop'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'web-ls-app-eus-ex-stg-01'
          slot-name: 'Production'
          publish-profile: ${{secrets.PUBLISH_PROFILE_STAGING}}
          package: ./

      - name: Deploy Web Application to Azure Production
        if: github.ref == 'refs/heads/master'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'web-ls-app-eus-ex-prd-01'
          slot-name: 'Production'
          publish-profile: ${{secrets.PUBLISH_PROFILE_PRODUCTION}}
          package: ./

